

version: '3'
services:
  node-1:
    image: leodotcloud/swiss-army-knife
    hostname: node-1
    networks:
      - net-0
      - net-A
  node-2:
    image: leodotcloud/swiss-army-knife
    hostname: node-2
    networks:
      - net-0
      - net-A
  node-3:
    image: leodotcloud/swiss-army-knife
    hostname: node-3
    networks:
      - net-0
      - net-B
  node-4:
    image: leodotcloud/swiss-army-knife
    hostname: node-4
    networks:
      - net-0
      - net-B
  node-5:
    image: leodotcloud/swiss-army-knife
    hostname: node-5
    networks:
      - net-0
      - net-B


networks:
  net-0:
  net-A:
  net-B:
 
  # node-1:
  # node-2:
  # node-3:
  # node-4:
  # node-5:

