

version: '3'

services:
  node-1:
    build: .
    hostname: node-1
    privileged: true
  node-2:
    build: .
    hostname: node-2
    privileged: true
  node-3:
    build: .
    hostname: node-3
    privileged: true
  node-4:
    build: .
    hostname: node-4
    privileged: true
  node-5:
    build: .
    hostname: node-5
    privileged: true


